import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Admin',
      email: 'x@x.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'User',
      email: 'y@y.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  items: [
    // {
    //   // _id: '1',
    //   name: 'Silver Milanese',
    //   slug: 'Silver Milanese',
    //   category: 'Smart watch',
    //   image: '/images/silver.jpg',
    //   price: 799.99,
    //   countInStock: 10,
    //   brand: 'Apple',
    //   rating: 4.5,
    //   numReviews: 10,
    //   description: 'shiny smart watch',
    // },
    // {
    //   // _id: '2',
    //   name: 'Gold Milanese',
    //   slug: 'Gold Milanese',
    //   category: 'Smart watch',
    //   image: '/images/gold.jpg',
    //   price: 799.99,
    //   countInStock: 0,
    //   brand: 'Apple',
    //   rating: 4.0,
    //   numReviews: 10,
    //   description: 'shiny smart watch',
    // },
    {
      // _id: '1',
      name: 'Midnight Sport M/L',
      slug: 'Midnight Sport M-L',
      // category: 'Smart watch',
      image: '/images/black.jpg',
      price: 530,
      countInStock: 0,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 14,
      description: 'black smart watch',
    },
    {
      // _id: '2',
      name: 'Red Sport M/L',
      slug: 'Red Sport M-L',
      // category: 'Smart watch',
      image: '/images/red.jpg',
      price: 530,
      countInStock: 5,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      description: 'red smart watch',
    },
    {
      // _id: '3',
      name: 'Midnight Sport',
      slug: 'Midnight Sport',
      // category: 'Smart watch',
      image: '/images/black.jpg',
      price: 530,
      countInStock: 1,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 14,
      description: 'black smart watch',
    },
    {
      // _id: '4',
      name: 'Starlight Sport',
      slug: 'Starlight Sport',
      // category: 'Smart watch',
      image: '/images/starlight.jpg',
      price: 530,
      countInStock: 5,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      description: 'cream-colored smart watch',
    },
    {
      // _id: '5',
      name: 'Red Sport',
      slug: 'Red Sport',
      // category: 'Smart watch',
      image: '/images/red.jpg',
      price: 530,
      countInStock: 5,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      description: 'red smart watch',
    },
    {
      // _id: '6',
      name: 'White Sport S/M',
      slug: 'White Sport S-M',
      // category: 'Smart watch',
      image: '/images/white.jpg',
      price: 530,
      countInStock: 5,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      description: 'white smart watch',
    },
    {
      // _id: '7',
      name: 'White Sport M/L',
      slug: 'White Sport M-L',
      // category: 'Smart watch',
      image: '/images/white.jpg',
      price: 529.99,
      countInStock: 5,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      description: 'white smart watch',
    },
  ],
};
export default data;
