import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'User1',
      email: 'x@x.com',
      password: bcrypt.hashSync('qwe'),
    },
    {
      name: 'User2',
      email: 'y@y.com',
      password: bcrypt.hashSync('qwe'),
    },
  ],
  items: [
    {
      name: 'Midnight Sport M/L',
      slug: 'Midnight Sport M-L',
      image: '/images/black.jpg',
      price: 530,
      stockCount: 0,
      brand: 'Apple',
      customerRating: 4.5,
      reviewCount: 14,
      description: 'black smart watch',
    },
    {
      name: 'Red Sport M/L',
      slug: 'Red Sport M-L',
      image: '/images/red.jpg',
      price: 530,
      stockCount: 5,
      brand: 'Apple',
      customerRating: 4.5,
      reviewCount: 10,
      description: 'red smart watch',
    },
    {
      name: 'Midnight Sport',
      slug: 'Midnight Sport',
      image: '/images/black.jpg',
      price: 530,
      stockCount: 1,
      brand: 'Apple',
      customerRating: 4.5,
      reviewCount: 14,
      description: 'black smart watch',
    },
    {
      name: 'Starlight Sport',
      slug: 'Starlight Sport',
      image: '/images/starlight.jpg',
      price: 530,
      stockCount: 5,
      brand: 'Apple',
      customerRating: 4.5,
      reviewCount: 10,
      description: 'cream-colored smart watch',
    },
    {
      name: 'Red Sport',
      slug: 'Red Sport',
      image: '/images/red.jpg',
      price: 530,
      stockCount: 5,
      brand: 'Apple',
      customerRating: 4.5,
      reviewCount: 10,
      description: 'red smart watch',
    },
    {
      name: 'White Sport S/M',
      slug: 'White Sport S-M',
      image: '/images/white.jpg',
      price: 530,
      stockCount: 5,
      brand: 'Apple',
      customerRating: 4.5,
      reviewCount: 10,
      description: 'white smart watch',
    },
    {
      name: 'White Sport M/L',
      slug: 'White Sport M-L',
      image: '/images/white.jpg',
      price: 530,
      stockCount: 5,
      brand: 'Apple',
      customerRating: 4.5,
      reviewCount: 10,
      description: 'white smart watch',
    },
  ],
};
export default data;
