const data = {
  items: [
    {
      _id: '1',
      name: 'Silver Milanese Loop',
      slug: 'Silver Milanese Loop',
      // category: 'Smart watch',
      image: '/images/silver.jpg',
      price: 799.99,
      countInStock: 10,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      description: 'shiny smart watch',
    },
    {
      _id: '2',
      name: 'Gold Milanese Loop',
      slug: 'Gold Milanese Loop',
      // category: 'Smart watch',
      image: '/images/gold.jpg',
      price: 799.99,
      countInStock: 0,
      brand: 'Apple',
      rating: 4.0,
      numReviews: 10,
      description: 'shiny smart watch',
    },
    {
      _id: '3',
      name: 'Midnight Sport Band S/M',
      slug: 'Midnight Sport Band S/M',
      // category: 'Smart watch',
      image: '/images/black.jpg',
      price: 529.99,
      countInStock: 1,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 14,
      description: 'black smart watch',
    },
    {
      _id: '4',
      name: 'Starlight Sport Band S/M',
      slug: 'Starlight Sport Band S/M',
      // category: 'Smart watch',
      image: '/images/starlight.jpg',
      price: 529.99,
      countInStock: 5,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      description: 'cream-colored smart watch',
    },
    {
      _id: '5',
      name: 'Red Sport Band S/M',
      slug: 'Red Sport Band S/M',
      // category: 'Smart watch',
      image: '/images/red.jpg',
      price: 529.99,
      countInStock: 5,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      description: 'red smart watch',
    },
    {
      _id: '6',
      name: 'White Sport Band S/M',
      slug: 'White Sport Band S/M',
      // category: 'Smart watch',
      image: '/images/white.jpg',
      price: 529.99,
      countInStock: 5,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      description: 'white smart watch',
    },
  ],
};
export default data;
